version: "3.5"
services:
  qa_system:
    container_name: qa_system
    build: 
      context: .
      dockerfile: Dockerfile
    image: qa_system
    environment:
      DATABASE_URL: mysql+pymysql://testuser:12345678@mysql:3306/qa-system-db
      AZURE_BLOB_CONTAINER: 
      AZURE_BLOB_CONNECTION_STRING: 
      AZURE_OPENAI_API_KEY: 
      AZURE_ENDPOINT: 
      AZURE_EMBEDDING_MODEL_NAME: 
      AZURE_CHAT_MODEL_NAME: 
      QDRANT_HOST: "qdrant"
      QDRANT_PORT: "6333"
    ports:
      - "8000:8000"
    restart: always
  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: testuser
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_PASSWORD: 12345678
      MYSQL_DATABASE: qa-system-db
    ports:
      - "3306:3306"
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant
    restart: always
    ports:
      - '6333:6333'
    volumes:
      - ./qdrant_storage:/qdrant/storage