version: "3.5"
services:
  app:
    container_name: LLM_APP
    build: 
      context: .
      dockerfile: Dockerfile
    image: llm
    environment:
      container_name: <YOUR_AZURE_BLOB_CONTAINER>
      connection_string: <YOUR_AZURE_BLOB_CONNECTION_STRING>
    ports:
      - "8000:8000"
    restart: always
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: <YOUR_USER_NAME>
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_PASSWORD: <YOUR_DATABASE_PASSWORD>
      MYSQL_DATABASE: <YOUR_DATABASE_NAME>
    ports:
      - "3306:3306"